name: compile-macosx-plugin
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Compile MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies and compile 
        run: |
          brew install gcc
          brew install eigen
          make all EIGEN=/usr/local/include/eigen3
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macosx-plugin
          path: src/build/manyiv_macosx.plugin
