name: compile-macosx-plugin
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: Compile MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: dependencies and compile 
        run: |
          brew install gcc
          brew install eigen
          make all EIGEN=/usr/local/include/eigen3
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.COMPILE_TOKEN }}
          file: src/build/manyiv_macosx.plugin
          tag: ${{ github.ref }}
          overwrite: true
